all:
  hosts:
    mirror:
      ansible_host: 187.77.179.206
      ansible_user: root
      spectoncr_registry_port: 5050
      spectoncr_auth_port: 5051
      spectoncr_metrics_port: 9095
      spectoncr_data_dir: /var/lib/spectoncr/data
      spectoncr_config_dir: /etc/spectoncr
      spectoncr_keys_dir: /etc/spectoncr/keys
