//! GitHub PR comment automation.
//!
//! Caller-driven: CI invokes the endpoint after a scan completes with the
//! repo + PR number + a short-lived token (GITHUB_TOKEN from the workflow,
//! or a PAT). We render a markdown summary from the scan and POST it to
//! GitHub's issue-comments endpoint, which services both issues and PRs.
//!
//! The token is used once and never stored. If a PR already has a comment
//! from a previous run for the same scan digest, we currently post a
//! fresh one — dedup could be layered in later by reading
//! `/issues/:n/comments` and comparing a marker string.

use reqwest::Client;
use serde::{Deserialize, Serialize};

use crate::model::{PolicyStatus, ScanResult, Severity, Vulnerability};

const MARKER: &str = "<!-- spectoncr-scan-summary -->";

#[derive(Debug, Deserialize)]
pub struct PrCommentRequest {
    /// `owner/repo`.
    pub repo: String,
    pub pr_number: u64,
    pub token: String,
    /// Optional GitHub Enterprise base URL (e.g. `https://github.acme.com/api/v3`).
    #[serde(default)]
    pub base_url: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct PrCommentReport {
    pub comment_id: u64,
    pub html_url: String,
}

pub fn render_comment(result: &ScanResult) -> String {
    let verdict = result
        .policy_evaluation
        .as_ref()
        .map(|pe| match pe.status {
            PolicyStatus::Pass => "✅ PASS",
            PolicyStatus::Fail => "❌ FAIL",
        })
        .unwrap_or("—");
    let summary = &result.summary;
    let mut out = String::new();
    out.push_str(MARKER);
    out.push_str("\n### SpectonCR scan: ");
    out.push_str(verdict);
    out.push_str("\n\n");
    out.push_str(&format!(
        "**Image**: `{}/{}/{}:{}` · **Digest**: `{}`\n\n",
        result.tenant,
        result.project,
        result.repository,
        result.reference,
        short_digest(&result.digest),
    ));
    out.push_str(&format!(
        "| Severity | Count |\n|---|---:|\n| 🔴 Critical | {c} |\n| 🟠 High | {h} |\n| 🟡 Medium | {m} |\n| 🔵 Low | {l} |\n\n",
        c = summary.critical, h = summary.high, m = summary.medium, l = summary.low
    ));

    // Top 5 criticals as a quick read.
    let mut crits: Vec<&Vulnerability> = result
        .vulnerabilities
        .iter()
        .filter(|v| !v.suppressed && matches!(v.severity, Severity::Critical))
        .collect();
    crits.sort_by(|a, b| {
        b.cvss_score
            .partial_cmp(&a.cvss_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    if !crits.is_empty() {
        out.push_str("**Top critical findings:**\n\n");
        for v in crits.into_iter().take(5) {
            out.push_str(&format!(
                "- `{}` — `{}@{}`{}\n",
                v.id,
                v.package,
                v.installed_version,
                v.fixed_version
                    .as_deref()
                    .map(|f| format!(" → fixed in `{}`", f))
                    .unwrap_or_default(),
            ));
        }
        out.push('\n');
    }
    out.push_str(&format!(
        "<sub>scan_id `{}` · generated by SpectonCR</sub>",
        result.id
    ));
    out
}

fn short_digest(d: &str) -> String {
    d.strip_prefix("sha256:")
        .unwrap_or(d)
        .chars()
        .take(12)
        .collect()
}

pub async fn post_comment(req: &PrCommentRequest, body: &str) -> Result<PrCommentReport, String> {
    let base = req
        .base_url
        .clone()
        .unwrap_or_else(|| "https://api.github.com".into());
    let url = format!(
        "{base}/repos/{repo}/issues/{n}/comments",
        base = base.trim_end_matches('/'),
        repo = req.repo,
        n = req.pr_number
    );
    let client = Client::new();
    let resp = client
        .post(&url)
        .bearer_auth(&req.token)
        .header("User-Agent", "spectoncr-scanner")
        .header("Accept", "application/vnd.github+json")
        .json(&serde_json::json!({"body": body}))
        .send()
        .await
        .map_err(|e| format!("github request failed: {e}"))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("github {status}: {body}"));
    }
    #[derive(Deserialize)]
    struct CommentResp {
        id: u64,
        html_url: String,
    }
    let c: CommentResp = resp
        .json()
        .await
        .map_err(|e| format!("github response decode: {e}"))?;
    Ok(PrCommentReport {
        comment_id: c.id,
        html_url: c.html_url,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;
    use chrono::Utc;
    use uuid::Uuid;

    fn mk() -> ScanResult {
        ScanResult {
            id: Uuid::nil(),
            digest: "sha256:abcdef123456".into(),
            tenant: "acme".into(),
            project: "web".into(),
            repository: "api".into(),
            reference: "1.0".into(),
            status: ScanStatus::Completed,
            error: None,
            started_at: Utc::now(),
            completed_at: Some(Utc::now()),
            summary: ScanSummary {
                critical: 2,
                high: 4,
                medium: 0,
                low: 0,
                unknown: 0,
            },
            vulnerabilities: vec![Vulnerability {
                id: "CVE-99".into(),
                aliases: vec![],
                package: "openssl".into(),
                ecosystem: "deb".into(),
                installed_version: "1.1.1".into(),
                fixed_version: Some("1.1.1k".into()),
                severity: Severity::Critical,
                cvss_score: Some(9.8),
                summary: None,
                description: None,
                layer_digest: None,
                references: vec![],
                suppressed: false,
            }],
            policy_evaluation: Some(PolicyEvaluation {
                status: PolicyStatus::Fail,
                violations: vec![],
                reason: None,
            }),
            packages: vec![],
        }
    }

    #[test]
    fn renders_fail_verdict_with_table() {
        let md = render_comment(&mk());
        assert!(md.contains("❌ FAIL"));
        assert!(md.contains("acme/web/api:1.0"));
        assert!(md.contains("CVE-99"));
        assert!(md.contains("1.1.1k"));
        assert!(md.contains(MARKER));
    }

    #[test]
    fn excludes_suppressed_from_top_criticals() {
        let mut r = mk();
        r.vulnerabilities[0].suppressed = true;
        let md = render_comment(&r);
        assert!(!md.contains("CVE-99"));
    }
}
