apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectoncr.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.registry.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.registry.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- if .Values.multiRegion.enabled }}
    - name: replication
      port: {{ .Values.multiRegion.internalPort }}
      targetPort: {{ .Values.multiRegion.internalPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "spectoncr.registry.selectorLabels" . | nindent 4 }}
