{{- if .Values.ingress.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectoncr.fullname" . }}-registry-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.registry.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "spectoncr.registry.selectorLabels" . | nindent 4 }}
{{- end }}
