{{- if not .Values.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.jwt.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jwt.signingKey }}
  signing.pem: {{ .Values.jwt.signingKey }}
  {{- else }}
  signing.pem: {{ "" | b64enc }}
  {{- end }}
  {{- if .Values.jwt.verificationKey }}
  verification.pem: {{ .Values.jwt.verificationKey }}
  {{- else }}
  verification.pem: {{ "" | b64enc }}
  {{- end }}
{{- if and .Values.oidc.enabled .Values.oidc.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.oidc.clientSecret | b64enc }}
{{- end }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "s3") (not .Values.storage.s3.existingSecret) .Values.storage.s3.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.s3.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.storage.s3.accessKeyField }}: {{ .Values.storage.s3.accessKey | b64enc }}
  {{ .Values.storage.s3.secretKeyField }}: {{ .Values.storage.s3.secretKey | b64enc }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "gcs") (not .Values.storage.gcs.existingSecret) .Values.storage.gcs.keyfile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.gcs.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.storage.gcs.keyfileField }}: {{ .Values.storage.gcs.keyfile | b64enc }}
{{- end }}
---
{{- if .Values.pullThroughCache.enabled }}
{{- range $name, $upstream := .Values.pullThroughCache.upstreams }}
{{- if and (not $upstream.existingSecret) $upstream.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.fullname" $ }}-upstream-{{ $name | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ default "username" $upstream.usernameField }}: {{ $upstream.username | b64enc }}
  {{ default "password" $upstream.passwordField }}: {{ $upstream.password | b64enc }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "azure") (not .Values.storage.azure.existingSecret) .Values.storage.azure.accountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spectoncr.azure.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectoncr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.storage.azure.accountKeyField }}: {{ .Values.storage.azure.accountKey | b64enc }}
{{- end }}
