//! Cargo `Cargo.lock` parser.
//!
//! The lockfile is TOML with `[[package]]` tables holding `name`, `version`,
//! and an optional `source`. We emit one `Package` per table whose `source`
//! is set (registry or git) — workspace members and path-only dependencies
//! have no `source` and are skipped, since they are not published crates
//! that any vuln database could track.

use serde::Deserialize;

use super::Package;

#[derive(Deserialize)]
struct Lock {
    #[serde(default)]
    package: Vec<LockPackage>,
}

#[derive(Deserialize)]
struct LockPackage {
    name: String,
    version: String,
    #[serde(default)]
    source: Option<String>,
}

pub fn parse(layer_digest: &str, contents: &[u8], out: &mut Vec<Package>) {
    let Ok(text) = std::str::from_utf8(contents) else {
        return;
    };
    let Ok(lock): Result<Lock, _> = toml::from_str(text) else {
        return;
    };
    for pkg in lock.package {
        if pkg.source.is_none() {
            continue;
        }
        out.push(Package {
            name: pkg.name.clone(),
            version: pkg.version.clone(),
            ecosystem: "cargo".into(),
            purl: format!("pkg:cargo/{}@{}", pkg.name, pkg.version),
            layer_digest: Some(layer_digest.to_string()),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = r#"
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "my-app"
version = "0.1.0"
# no source — workspace member, should be excluded

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"

[[package]]
name = "tokio"
version = "1.35.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbb"
dependencies = ["mio"]

[[package]]
name = "local-dep"
version = "0.1.0"
# path dep, no source — excluded

[[package]]
name = "some-git-crate"
version = "0.2.0"
source = "git+https://github.com/foo/bar.git#abc123"
"#;

    #[test]
    fn parses_cargo_lock_excluding_sourceless() {
        let mut out = Vec::new();
        parse("sha256:cl", FIXTURE.as_bytes(), &mut out);
        let names: Vec<&str> = out.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(out.len(), 3, "got: {:?}", names);
        assert!(names.contains(&"serde"));
        assert!(names.contains(&"tokio"));
        assert!(names.contains(&"some-git-crate"));
        assert!(
            !names.contains(&"my-app"),
            "workspace root must be excluded"
        );
        assert!(!names.contains(&"local-dep"), "path dep must be excluded");

        let serde = out.iter().find(|p| p.name == "serde").unwrap();
        assert_eq!(serde.version, "1.0.193");
        assert_eq!(serde.ecosystem, "cargo");
        assert_eq!(serde.purl, "pkg:cargo/serde@1.0.193");
        assert_eq!(serde.layer_digest.as_deref(), Some("sha256:cl"));
    }

    #[test]
    fn malformed_toml_yields_nothing() {
        let mut out = Vec::new();
        parse("sha256:l", b"not valid toml [[[[", &mut out);
        assert!(out.is_empty());
    }

    #[test]
    fn empty_lockfile_yields_nothing() {
        let mut out = Vec::new();
        parse("sha256:l", b"version = 3\n", &mut out);
        assert!(out.is_empty());
    }
}
